"""add imagehead hash

Revision ID: 1f392ed7b75f
Revises: 2374bd9e185c
Create Date: 2016-11-06 17:00:50.716421

"""

# revision identifiers, used by Alembic.
revision = '1f392ed7b75f'
down_revision = '2374bd9e185c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
