"""add body_html

Revision ID: 845fb6ff9143
Revises: 361659bc7895
Create Date: 2016-11-19 10:59:38.521834

"""

# revision identifiers, used by Alembic.
revision = '845fb6ff9143'
down_revision = '361659bc7895'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
