"""initial migration

Revision ID: 847be2bf9771
Revises: None
Create Date: 2016-11-05 13:40:28.247907

"""

# revision identifiers, used by Alembic.
revision = '847be2bf9771'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('defult', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_defult'), 'roles', ['defult'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_defult'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'defult')
    ### end Alembic commands ###
