"""add confired

Revision ID: cde39f4b975d
Revises: None
Create Date: 2016-10-30 11:07:03.797572

"""

# revision identifiers, used by Alembic.
revision = 'cde39f4b975d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
